language: c
dist: bionic

notifications:
  email: false

before_install:
  sudo apt-get install -y libsqlite3-dev cppcheck valgrind gcc-4.8 gettext libc6-dev-armhf-cross libc6-dev-arm64-cross gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf qemu-user-static binfmt-support libsecp256k1-dev

env:
  - VALGRIND=0 ARCH=64 DEVELOPER=0 COMPILER=gcc COMPAT=0
cache:
  directories:
    - dependencies

script:
  .travis/build.sh
