sudo: required
dist: trusty
language: c
before_install:
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo add-apt-repository ppa:ondrej/pkg-nlnetlabs -y || true # This fails due to UTF-8 in the author's name...
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get -qq update
install:
  - sudo apt-get install -y --no-install-recommends bitcoind build-essential automake eatmydata net-tools libtool libprotobuf-c-dev libsodium-dev libsqlite3-dev valgrind protobuf-c-compiler libgmp-dev
  - git clone https://github.com/luke-jr/libbase58.git libbase58; cd libbase58; ./autogen.sh; ./configure; make; sudo make install; cd ..
  - git clone https://github.com/rustyrussell/lightning-rfc.git ../lightning-rfc
compiler:
  - gcc
script:
  - make clean
  - make
  - make full-check
after_failure:
  - sudo killall lightningd
  - sudo kill `ps aux | grep lightningd | grep -v grep | awk '{print $2}'`;
  - tar -cvjf /tmp/travis-run.tar.bz2 /tmp/lightning.*.?;
  - curl --upload-file /tmp/travis-run.tar.bz2 https://transfer.sh/travis-run.tar.bz2;
env:
  global:
    - LD_LIBRARY_PATH=/usr/local/lib
